language: scala
scala:
- 2.11.7
jdk:
- oraclejdk8
env:
  global:
  - secure: pTVs9kg3bz14JeEvP92k8Q6vxr36KptTQzVRNnmbWbtjccBY3BHd2mon45XJ4Zyn6H+DyPULTMmqXulXrgwTEAy1CetsTko/z7mF7O7i0SXMH17EBYIJRbrq0kbQyO0jS0D3g9DCJmzXpC7pZTqPfNrOZxuFM54pxXOC2+EDK3uRD8ruXByUzUTi+5VToc4mZH7lQZByQeIe9MmkxBvfRtIVeAIKd1rCdRjvSPWe7sOBBXbmGl3JdwVK/68jsX2Q4Bay5AKqOz64p8YJTQ5iRdEowL6s7cq91DxJC+ygbtHR+xIlz8FS4OuPKk0t0UB0jUh+kcvq5pIKWt0ne2VaYMC1buhLkQ7UCR9a/7CMyfqBaOQQX0eIFnjKbo+RSHh3gHrIn6hvHvr/55GfsjCr0rXf8n279QxLSRPWduAaJjTotl9TNYLWb+Xn2e96boHxYhtuSxxH1/6epRwwtq2UNVJPhV3WuvOSZ0imnaG5z9bmYyozHSh92clJtN45tyD0jZYy0ccGdpZRi5A85iaQPqaFO8rHwn2HQ1ggwVXBWfup/1uf/vKwyHKFXMwa9kQ4crS8InOQk7U7XHoEK4H4Mlpt/wc1lES3gO1D3r6NurZ82+L4oJIcdUftThwpPaf8jA+1hehICJmZSRg5DT3/NQQ9mwP8bkt+jxMAwACiZUI=
  - secure: fi5PA+nSd8gPduM1r0bs/tsHANikcNLj05rcROfgXqhA916OJMIvQBgM86uq0adml89BLlsvnMqM81LWelXhdV7BtEmdGV7hfBFwnsFCPzqx3VhaYgMAsMfpSmnaoVqZ4ivTCbLToWjMZoViKZt7AZLMxR58UGFqR5s4v+iH/X1rIjTos42ZEWERT+yLd/KgxWyNO9ys3OzD8NlqQoEugWEXC0B5ihDnocaPc7m4g8ftHIfXTfs+QZptHjCtf63B4apDueo8GLUYWKl9El0LcbUuh7IZnnKLdHKKPESezBNUaswefRQgt1gNCmUZmULS5nMAaU2fzhRjE8SIZSuvVqxRJByz2hR8igDdd0FYeD9W0akVKPCQXJPG1HXutC6QKkCu6GGXhTt7cOnobQCQFl7ekdexBPFeZSUk6K1KLWYDstJtwW/0qAPhraRCzgvQ0bRK79qgH1TFA25jvGVY+QP7+xq2FopIwTXP3/2wXGEvUkGLmrL+KKtodOJN+9C332LIkXL9v0+TbE6wpByQb/8vBlnQChetVhBzGWz+8OCb/v20ymIzSseJfxUKqlNeD+7yhxf/1sAiurMuJ3P3cZQbLjD4D2giD1/ExuCmnqPFCozeXrD/jwXwtzcN2UYSVhEaMzZgeC6DIXL6qs1hAOgvqxMZiAfSIeIQUhxcXec=
script:
- sbt ++$TRAVIS_SCALA_VERSION clean coverage test && sbt ++$TRAVIS_SCALA_VERSION coverageAggregate
- sbt "crawler/assembly" && sbt "portal/dist"
- scripts/aws/bundle.sh
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: s3
  access_key_id: AKIAIA4EERMFHRPPQIRQ
  secret_access_key:
    secure: "SGaRRgnlxi4JijMO05vDf9/QsbXElQgFg0UveHUKP9yTBDHkSY1uJTCU6r+ZYjVQkACV3jIO2tHm4I7mfnz+gyGCR7XBXTKTb1AR1Itm8ZrneYZICeoENsZtk0N7trhsUpyx3f7CCXd+sjD4oyoTur2TdaHfBJL2CR/yhtlYhGqSY7+98YIXQGlY3kCx568wzCELltGitKJTjZI6dUHi8Qifk/WZs1b+ykowfQVo+cPVOKvrdykz8lN2Ovv8x8MjaCA2UxSGKeJH4jNFn7sz3dAeWDwroKTUyrgNFv2cqpIhm+W4733Nzyxy3WxJQPsfJTx0Nlj6FJDghOy0fbDtSzOW6qTNA1vjHuIi93xcg3f40K5QrvX3dMFyiX0NYxX3WWvrw7orZJjylVyneKsINU30mWDpBQNTJ/YeyUD3i8S038Cw/71IqHjo1+yWgjk1VuZvsPso0vhUMS9dwdBMCX9gUaXjPhQn65jaYUNx3MMXCTPkNSyBwMl1etIoa5wAj3wv0oGNJvyYMnOaLW+IQf7tuipfBZozPf0X9e9nVHfcUkK4r40vYeEsNA3yc0wOy0arbIsRYQfdHr46nFYpSmqmPR7kAVVzqySXX7RJI6uZ567WziAHH+Hjh1zC9rQHeITRkbuNyBjU1IirChWMTGRj+Ek94FPLJLPOaGLrKDk="
  region: eu-west-1
  bucket: fotm-info-staging-bucket
  skip_cleanup: true
  local_dir: revision/artifact
