language: scala

scala:
   - 2.11.7

jdk:
  - oraclejdk8

#script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test && sbt ++$TRAVIS_SCALA_VERSION coverageAggregate

script: ./deploy_gcvm.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_install:
- openssl aes-256-cbc -K $encrypted_e3249f0070eb_key -iv $encrypted_e3249f0070eb_iv
  -in google_compute_engine.ssh.enc -out google_compute_engine.ssh -d
