language: scala

scala:
   - 2.11.7

jdk:
  - oraclejdk8

#script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test && sbt ++$TRAVIS_SCALA_VERSION coverageAggregate

script: ./deploy_gcvm.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
